core/urls.py
from django.contrib import admin
from django.urls import path
from main.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello-world/', hello_world),
    path('today/', today_view),
    path('talabalar/', talabalar_view),
    path('talabalar/<int:talaba_id>/', talaba_details_view),
    path('mualliflar/', mualliflar_view),
    path('', home_view),
    path('mualliflar/<int:muallif_id>/', muallif_details_view),
    path('kitoblar/', kitoblar_view),
    path('recordlar/', recordlar_view),
    path('top3-kitoblar/', top3_kitoblar_view)





]

main/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class Talaba(models.Model):
    name = models.CharField(max_length=255)
    guruh = models.CharField(max_length=100, blank=True, null=True)
    kurs = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    kitob_soni = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Talaba'
        verbose_name_plural = 'Talabalar'


class Muallif(models.Model):
    gender_choices = (
        ('Male', 'Male'),
        ('Female', 'Female')
    )
    name = models.CharField(max_length=255)
    jinsi = models.CharField(max_length=10, choices=gender_choices)
    birth_date = models.DateField(blank=True, null=True)
    kitoblar_soni = models.PositiveSmallIntegerField(blank=True, null=True)
    tirik = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Muallif'
        verbose_name_plural = 'Mualliflar'


class Kitob(models.Model):
    name = models.CharField(max_length=255)
    janri = models.CharField(max_length=100, blank=True, null=True)
    sahifa = models.PositiveSmallIntegerField(blank=True, null=True)
    muallif = models.ForeignKey(Muallif, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Kitob'
        verbose_name_plural = 'Kitoblar'


class Kutubxonachi(models.Model):
    name = models.CharField(max_length=255)
    ish_vaqti = models.DurationField(default=10)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Kutubxonachi'
        verbose_name_plural = 'Kutubxonachilar'


class Record(models.Model):
    talaba = models.ForeignKey(Talaba, on_delete=models.SET_NULL, null=True)
    kitob = models.ForeignKey(Kitob, on_delete=models.SET_NULL, null=True)
    kutubxonachi = models.ForeignKey(Kutubxonachi, on_delete=models.SET_NULL, null=True)
    olingan_sana = models.DateTimeField(auto_now_add=True)
    qaytardi = models.BooleanField(default=False)
    qaytarish_sana = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f"{self.talaba.name} - {self.kitob.name}"

    class Meta:
        verbose_name = 'Record'
        verbose_name_plural = 'Recordlar'

main/views.py
from django.shortcuts import render
from .models import *
from django.http import HttpResponse


def hello_world(request):
    return HttpResponse("<h1>Hello World!</h1>")


def today_view(request):
    import datetime
    today = datetime.date.today()
    context = {
        'today': today
    }
    return render(request, 'today.html', context)


def home_view(request):
    return render(request, 'home.html')


def talabalar_view(request):
    talabalar = Talaba.objects.all()
    context = {
        'talabalar': talabalar
    }
    return render(request, 'talabalar.html', context)


def talaba_details_view(request, talaba_id):
    talaba = Talaba.objects.get(id=talaba_id)
    context = {
        'talaba': talaba
    }
    return render(request, 'talaba_details.html', context)


def mualliflar_view(request):
    mualliflar = Muallif.objects.all()
    context = {
        'mualliflar': mualliflar
    }
    return render(request, 'mualliflar.html', context)


def muallif_details_view(request, muallif_id):
    muallif = Muallif.objects.get(id=muallif_id)
    kitoblar = Kitob.objects.filter(muallif=muallif)
    context = {
        'muallif': muallif,
        'kitoblar': kitoblar
    }
    return render(request, 'muallif_details.html', context)


def kitoblar_view(request):
    kitoblar = Kitob.objects.all()
    context = {
        'kitoblar': kitoblar
    }
    return render(request, 'kitoblar_view.html', context)


def top3_kitoblar_view(request):
    kitoblar = Kitob.objects.order_by('-sahifa')[:3]
    context = {
        'kitoblar': kitoblar
    }
    return render(request, 'top3-kitoblar.html', context)


def recordlar_view(request):
    recordlar = Record.objects.all()
    context = {
        'record': recordlar
    }
    return render(request, 'recordlar_view.html', context)

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bosh sahifa</title>
</head>
<body>
<h1>Kutubxona loyihasi</h1>
<hr>
<a href="/talabalar/">Talabalar</a>
<a href="/mualliflar/">Mualliflar</a>
<a href="/kitoblar/">Kitoblar</a>
<a href="/kutubxonachilar/">Kutubxonachilar</a>
<a href="/record/">Recordlar</a>
<br><br>
<a href="/top3_kitoblar/">Top 3 sahiflali kitoblar</a>
</body>
</html>

templates/kitoblar_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Kitoblar ro'yxati</title>
</head>
<body>
<h1>Kitoblar ro'yxati</h1>
<hr>
{%for kitob in kitoblar%}
    <p>{{forloop.counter}}. {{kitob.name}}</p>
{%endfor%}
</body>
</html>

templates/muallif_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Muallif | {{ muallif.name }}</title>
</head>
<body>
<h1>{{ muallif.name }} ma'lumotlari</h1>
<a href="mualliflar/">Mualliflar ro'yxati</a>
<hr>
<p>Jins: {{ muallif.jinsi }}</p>
<p>Tug'ilgan sana: {{ muallif.birth_date }}</p>
<p>Kitoblar soni: {{ muallif.kitoblar_soni }}</p>
<p>Tirik: {{ muallif.tirik }}</p>
<hr>
<h2>Kitoblari</h2>
{% for kitob in muallif.kitob_set.all %}
<p>{{ forloop.counter }}. {{kitob.name}}</p>
{%endfor%}
</body>
</html>

templates/mualliflar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mualliflar ro'yhati</title>
</head>
<h1>Mualliflar ro'yxati</h1>
<a href="/">Bosh sahifa</a>
<hr>
<body>
{%for muallif in mualliflar%}
    <p>{{forloop.counter}}.
        <a href="/mualliflar/{{muallif.id}}/">
            {{muallif.name}}
        </a>
    </p>
{% endfor %}
</body>
</html>

templates/recordlar_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Recordlar ro'yxati</title>
</head>
<body>
<h1>Recordlar ro'yxati</h1>
<hr>
<p>Talaba: {{record.talaba.name}}</p>
<p>Kitob: {{record.kitob.name}}</p>
<p>Kutubxonachi: {{record.kutubxonachi.name}}</p>
<p>Olingan sana: {{record.olingan_sana}}</p>
<p>Qaytardi: {{record.qaytardi}}</p>
<p>Qaytarish sanasi: {{record.qaytarish_sana}}</p>
</body>
</html>

templates/talaba_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Talabalar | {{talaba.name}}</title>
</head>
<body>
<h1>{{talaba.name}} ma'lumotlari</h1>
<a href="/talabalar/">Talabalar ro'yxati</a>
<br><br>
<a href="/">Bosh sahifa</a>
<hr>
<p>Guruh: {{talaba.guruh}}</p>
<p>Kursi: {{talaba.kurs}}</p>
<p>Kitob soni: {{talaba.kitob_soni}} ta</p>

</body>
</html>

templates/talabalar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Talabalar ro'yxati</title>
</head>
<body>
<h1>Talabalar ro'yxati</h1>
<a href="/">
    Bosh sahifa
</a>
<hr>
{% for talaba in talabalar %}
    <p>{{ forloop.counter }}.
        <a href="/talabalar/{{ talaba.id }}">
            {{ talaba.name }}
        </a>
    </p>
{% endfor %}
</body>
</html>

templates/today.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->

<!--</body>-->
<!--</html>-->
<p>{{today}}</p>

templates/top3-kitoblar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Top 3 sahifali kitoblar</title>
</head>
<body>
{%for kitob in kitoblar%}
<p>{{forloop.counter}}. {{kitob.name}} - {{kitob.sahifa}} sahifa</p>
{%endfor%}
</body>
</html>